site_name: Earth Observer

dev_addr: 127.0.0.1:8888

theme:
  name: material
  locale: en
  palette:
    scheme: geoid
    # primary: light blue
  logo: assets/logo.png
  favicon: assets/images/favicon.png
  # features:
  #   - navigation.tabs

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX
  social:
    - icon: fontawesome/solid/globe 
      link: https://www.geoid.org
    - icon: fontawesome/brands/github 
      link: https://github.com/geoid-org
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/geoid-org
    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/geoid_org
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/geoid.org

copyright: Copyright &copy; 2023 Geoid

hide:
  - footer




pages:
  - Getting Started:
      - 'Introduction': 'index.md'
  - Resources:
      - 'Portals': 'resources/portals.md'
  - Glossary: 'glossary.md'
  - License: 'license.md'
  - Privacy Policy: 'privacy.md'