site_name: Earth Observer
site_url: https://www.earth.observer/
site_description:
site_author:
copyright:
lang: en

repo_name: 'GitHub'
repo_url: https://github.com/geoid-org/earth-observer/
edit_uri_template: 'docs/{path}'

dev_addr: 127.0.0.1:8888

theme:
  name: material
  locale: en
  palette:
    scheme: geoid
    # primary: light blue
  logo: assets/image/logo_light.png
  favicon: assets/favicon/favicon.png
  features:
    - navigation.tabs

extra_css:
  - assets/style/extra.css
extra_javascript:
  - assets/script/extra.js
extra_templates:

extra:
  generator: false
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX
  social:
    - icon: fontawesome/solid/globe 
      link: https://www.geoid.org
    - icon: fontawesome/brands/github 
      link: https://github.com/geoid-org
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/geoid-org
    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/geoid_org
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/geoid.org

copyright: Copyright &copy; 2023 Geoid

hide:
  - footer




nav:
  - Getting Started:
      - 'Introduction': 'index.md'
  - Resources:
      - 'Portals': 'resources/portals.md'
  - Glossary: 'glossary.md'
  - License: 'license.md'
  - Privacy Policy: 'privacy.md'